sudo: required

services:
  - docker

language: ruby

rvm:
  - 1.9.3
addons:
  firefox: "38.0.5" 

before_install:
  - docker pull denmanjd/testapp
  - docker run -d --name test_container -p 127.0.0.1:80:4567 denmanjd/testapp
  - docker ps -a
  - sudo docker exec demo_container bin/rake spec
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
